// Generates infra/dns/zonymouslabs.com.zone.
//
// Every value here was read from a live DNS query or the Firebase Hosting API,
// never transcribed from the Vercel panel — its font renders the DKIM key's
// `9w0B` (zero) as `9wOB` (capital O), which would silently break signing.
import fs from 'node:fs';

const TTL = 300; // low while migrating, so a mistake is quick to undo

// --- carried over from Vercel, verified by query --------------------------
const DKIM = 'v=DKIM1;k=rsa;p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqaOpFJO9UArtii+KgQv+Xl8XyOhIec6Vcx+QtPgxgUU+IKZNpZjrFDkMLW9O/rAdcvg38Xz8MlOoVA0T1CFxfM6FuZRGDYh2KyhVCc0J6XGbNvcxxnIS7t74zi/C8O9GOKh7HTxcuCbQLHJDgtQ08jHrSE43KuVTthEwZewz6nqB1tjkZF+IGKQEdEnavDzmuj2WZiqFP+ro/WXhp76K6qQbxpFLuU0g87M7g+28pFE8E5efOCppqD93Hjsp1nLUXFD6SFMX/Jb2f/rwhSKTGrfhDhaL6tkB7Uk3GoX/Vlg9Q2EknXvs6jePEIXv+fIYvUbgrN1jD00gVG74xC6+oQIDAQAB';
const SPF = 'v=spf1 include:spf.spacemail.com ~all';

// --- required by Firebase Hosting -----------------------------------------
const FIREBASE_A = '199.36.158.100';
const SITE_TXT = 'hosting-site=zonymous-website';
const ACME_APEX = '1UvoRbs6uiQFs4QnKCHVChd3AE_RqFwiCswg1MJIc5g';
const ACME_WWW = 'usePORnU_an2YtOq0gPiokg9AhNfT47DfWRUMtvhgAo';

/** A TXT string is capped at 255 bytes; longer values ship as adjacent strings. */
const txt = (v) => {
  const parts = v.match(/.{1,255}/g) ?? [];
  return parts.map((p) => `"${p}"`).join(' ');
};

const lines = [
  '; zonymouslabs.com — Cloud DNS zone',
  '; Generated by infra/dns/build-zone.mjs. Edit the script, not this file.',
  ';',
  '; Deliberately NOT carried over from Vercel:',
  ';   *      ALIAS cname.vercel-dns-017.com.        (wildcard — Vercel routing only)',
  ';   @      ALIAS 3dd7f720c7ad4051.vercel-dns-017.com.',
  '; The wildcard is why every probed subdomain used to resolve. Dropping it means',
  '; www needs its own record, which it now has.',
  '',
  `$TTL ${TTL}`,
  '',
  '; --- site ---',
  `zonymouslabs.com.                      ${TTL} IN A     ${FIREBASE_A}`,
  `www.zonymouslabs.com.                  ${TTL} IN CNAME zonymous-website.web.app.`,
  '',
  '; --- email (Spacemail) — do not touch without checking deliverability ---',
  `zonymouslabs.com.                      ${TTL} IN MX    0 mx1.spacemail.com.`,
  `zonymouslabs.com.                      ${TTL} IN MX    0 mx2.spacemail.com.`,
  `zonymouslabs.com.                      ${TTL} IN TXT   ${txt(SPF)}`,
  `spacemail._domainkey.zonymouslabs.com. ${TTL} IN TXT   ${txt(DKIM)}`,
  '',
  '; --- Firebase Hosting ownership + ACME cert validation ---',
  `zonymouslabs.com.                      ${TTL} IN TXT   ${txt(SITE_TXT)}`,
  `_acme-challenge.zonymouslabs.com.      ${TTL} IN TXT   ${txt(ACME_APEX)}`,
  `_acme-challenge.www.zonymouslabs.com.  ${TTL} IN TXT   ${txt(ACME_WWW)}`,
  '',
  '; --- CAA: who may issue certs. pki.goog + letsencrypt cover Firebase. ---',
  `zonymouslabs.com.                      ${TTL} IN CAA   0 issue "pki.goog"`,
  `zonymouslabs.com.                      ${TTL} IN CAA   0 issue "letsencrypt.org"`,
  `zonymouslabs.com.                      ${TTL} IN CAA   0 issue "sectigo.com"`,
  '',
];

fs.writeFileSync('infra/dns/zonymouslabs.com.zone', lines.join('\n'));
console.log(`DKIM is ${DKIM.length} chars -> ${txt(DKIM).split('" "').length} TXT string(s)`);
console.log('wrote infra/dns/zonymouslabs.com.zone');
